name: Build pdfalto on Linux

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up environment
        run: |
          if [ $RUNNER_OS = 'Linux' ]; then
            sudo apt-get update -qq
            sudo apt-get install -qq cmake build-essential
          elif [ $RUNNER_OS = 'macOS' ]; then
            brew update
            brew upgrade cmake
          fi

      - name: Display versions
        run: |
          gcc -v
          g++ -v
          cmake --version

      - name: Configure with CMake
        run: cmake ./

      - name: Build
        run: make
