# This workflow builds pdfalto for Windows server using Cygwin

name: Build pdfalto (Windows)

runs-on: windows-latest

env:
  CYGWIN_ROOT: /cygdrive/c/cygwin64

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Cygwin and dependencies (using runners with Cygwin pre-installed)
        run: |
          # Consider using a runner with Cygwin pre-installed for efficiency
          # If Cygwin is not pre-installed, uncomment and customize these lines:
          # choco install git cygwin cyg-get -y
          # cyg-get install make gcc-g++ autoconf libtool libxml2-devel automake zlib-devel

      - name: Setup Cygwin environment (assuming Cygwin is pre-installed)
        # Adjust paths if Cygwin is installed in a different location
        run: |
          set PATH=$CYGWIN_ROOT/bin:$PATH
          export CC=/cygwin/bin/gcc
          export CXX=/cygwin/bin/g++

      - name: Clone pdfalto repository
        run: |
          git clone https://github.com/kermitt2/pdfalto.git

      - name: Navigate to pdfalto directory
        run: |
          cd pdfalto

      - name: Download Xpdf submodule (using SSH key for security)
        uses: actions/checkout@v3
        with:
          repository: https://github.com/jdhieux/xpdf
          subdirectory: xpdf-4.03
          fetch-depth: 1
          # Consider using a pre-generated SSH key stored as a GitHub Secret
          # for secure authentication:
          # env:
          #   GIT_SSH_COMMAND: 'ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_KEY }}'

      - name: Build pdfalto
        run: |
          sh ./autogen.sh  # Run if present
          ./configure
          make

      - name: Upload artifacts (optional)
        uses: actions/upload-artifact@v3
        with:
          name: pdfalto-windows
          path: ./build/pdfalto.exe
